---

- name: ANTRL | Get sources
  become: true
  get_url: url={{url}} dest={{tmp}} timeout=180 force=no
  register: antrl_downloaded

- name: ANTRL | Create Install Dir
  file:
    path: "{{install_dir}}"
    state: directory

- name: ANTLR | copy to install
  ansible.builtin.copy:
    remote_src: yes
    src: "{{tmp}}/{{jar}}"
    dest: "{{install_dir}}"
    mode: '0644'

# Environment setup.
- name: ANTRL | add to CLASSPATH
  template:
    src: java_home.sh.j2
    dest: /etc/profile.d/java_home.sh
    mode: 0644
